-- The catalogue: what a product IS. What there is of it belongs to inventory-service.
--
-- STARTING AGAIN AT V1, like inventory-service did. The application's history reached V13 getting
-- this table to its current shape across four migrations - V1 created it, V3 added the category,
-- V4 added the optimistic-lock version, V8 indexed the name, V11 took stock_quantity away. None of
-- that history is replayed here, because a new database has nothing to migrate FROM. What is
-- carried over is the SHAPE, verbatim: this is a deployment change, and it must not also be a data
-- change.
--
-- The shape below was read from the running database rather than reconstructed from the four
-- migrations, which is the only way to be sure the two agree.
CREATE TABLE product (
    -- GENERATED BY DEFAULT AS IDENTITY, not ALWAYS, and the distinction matters more here than it
    -- did in the monolith: "BY DEFAULT" still allows an explicit id to be inserted, which is what
    -- lets the seed below decide its own ids - and inventory_db's seed is keyed to those ids.
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(1000),

    -- NUMERIC(12,2), never a float. Money in binary floating point cannot represent 0.10 exactly,
    -- and the error compounds over a total. This is the column @Column(precision, scale) and
    -- BigDecimal exist to match.
    price       NUMERIC(12, 2) NOT NULL,

    category    VARCHAR(50),

    -- The optimistic lock for the PRODUCT's own fields. Phase 20a moved the stock lock out to
    -- product_stock precisely so that a checkout and an administrator editing a description would
    -- stop colliding over one version column. They are in different databases now, so they cannot
    -- collide even in principle - but this one still guards two administrators editing at once.
    version     BIGINT         NOT NULL DEFAULT 0
);

-- Both indexes come over with the table. `idx_product_name` was Phase 8's answer to the search
-- endpoint's sequential scan; `idx_product_category` backs filtering by category.
CREATE INDEX idx_product_name ON product (name);
CREATE INDEX idx_product_category ON product (category);
