-- Phase 27: every description an LLM wrote, kept.
--
-- The winning description is also copied onto product.description, because that is what a shopper
-- reads. This table is the rest of the answer - the tags and the SEO title, which have no column
-- on product yet - and the record of HOW it was made: which model, and how many tokens it cost.
-- Generated text is a thing an administrator may later have to explain ("where did this claim come
-- from?"), and "the model said so, on this date, with this model" is only answerable if it was
-- written down at the time.
CREATE TABLE product_description_generation (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ON DELETE CASCADE: the history belongs to the product. Deleting a product through the API is
    -- one DELETE on product, and a foreign key without a cascade would turn that into a 500.
    product_id        BIGINT        NOT NULL REFERENCES product (id) ON DELETE CASCADE,

    -- The same limit as product.description, so a generation that is saved can always be applied.
    description       VARCHAR(1000) NOT NULL,
    seo_title         VARCHAR(70)   NOT NULL,

    -- Comma-separated. The tags are only ever read back as a set with the row, never searched, and
    -- a join table for a list nobody queries is ceremony. Phase 28 (semantic search) will revisit
    -- how products are found.
    tags              VARCHAR(500)  NOT NULL,

    model             VARCHAR(100),
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    generated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_description_generation_product ON product_description_generation (product_id);
