-- Phase 28: semantic search. Four things, all owned by catalog-service:
--   1. the pgvector extension and the table holding one embedding per product;
--   2. the outbox, so every product change announces itself in its own transaction;
--   3. Spring Batch's JobRepository tables, for the backfill;
--   4. a REINDEX of the two text indexes, because the database image changed underneath them.

-- ------------------------------------------------------------------------------------------
-- 1. pgvector
-- ------------------------------------------------------------------------------------------
-- The extension ships in the pgvector/pgvector image, not in postgres:18-alpine, which is why the
-- catalogue's database image changed in this phase. CREATE EXTENSION needs a superuser, and the
-- image's POSTGRES_USER is one; a managed database (RDS, Azure) allow-lists `vector` instead.
CREATE EXTENSION IF NOT EXISTS vector;

-- The column layout is Spring AI's PgVectorStore's own (id, content, metadata, embedding), written
-- here rather than by `initialize-schema=true`, for the reason every other table in this service is
-- a migration: the schema is versioned, reviewed and the same everywhere. The store is built with
-- its table validation on, so a drift between this file and the library fails at startup.
--
-- id IS THE PRODUCT'S ID, not a random UUID. One product has exactly one embedding, so upserting
-- by product id is idempotent: the indexer may process the same event twice (two outbox relays,
-- a redelivery) and the second write simply replaces the first. And the foreign key makes a
-- deleted product's embedding disappear in the same statement - search can never return a product
-- that no longer exists because a delete event was lost.
--
-- vector(768): both supported models produce 768 numbers - Ollama's nomic-embed-text natively,
-- OpenAI's text-embedding-3-small when asked for 768 (it can shorten its 1536). A model with a
-- different size needs a new migration and a re-embed of everything: vectors from two models live
-- in two different spaces, so mixing them would compare nonsense with nonsense.
CREATE TABLE product_embedding (
    id        BIGINT PRIMARY KEY REFERENCES product (id) ON DELETE CASCADE,
    content   TEXT,
    metadata  JSON,
    embedding vector(768)
);

-- HNSW: a graph index for APPROXIMATE nearest neighbours. Without it every search compares the
-- query with every row (exact, and linear in the catalogue); with it a search walks a few hops of
-- a layered graph. vector_cosine_ops because the store ranks by cosine distance (1 - cosine
-- similarity): direction, not length, is what carries the meaning of a text embedding.
-- Ten products do not need an index. It is here because the phase is about how this scales, and
-- because an index added later is a migration on a big table.
CREATE INDEX idx_product_embedding_hnsw ON product_embedding USING hnsw (embedding vector_cosine_ops);

-- ------------------------------------------------------------------------------------------
-- 2. The outbox (the shared library's tables; the same DDL as inventory-service's V3)
-- ------------------------------------------------------------------------------------------
CREATE TABLE outbox_event (
    id              BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID                        NOT NULL UNIQUE,
    aggregate_type  VARCHAR(100)                NOT NULL,
    aggregate_id    VARCHAR(100)                NOT NULL,
    event_type      VARCHAR(100)                NOT NULL,
    payload         TEXT                        NOT NULL,
    trace_parent    VARCHAR(55),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP(6) WITH TIME ZONE,
    attempts        INTEGER                     NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000)
);

CREATE INDEX idx_outbox_event_pending ON outbox_event (published_at, id);
CREATE INDEX idx_outbox_event_published_at ON outbox_event (published_at);

-- The library maps it, so it must exist. This service's indexer does not use it: re-embedding the
-- CURRENT state of a product is idempotent by itself, so there is no duplicate to refuse.
CREATE TABLE processed_event (
    event_id     UUID                        PRIMARY KEY,
    event_type   VARCHAR(100)                NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_processed_event_processed_at ON processed_event (processed_at);

-- ------------------------------------------------------------------------------------------
-- 3. Spring Batch 6's JobRepository (schema-postgresql.sql from spring-batch-core 6.0.5, verbatim)
-- ------------------------------------------------------------------------------------------
CREATE TABLE BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME VARCHAR(100) NOT NULL,
	PARAMETER_TYPE VARCHAR(100) NOT NULL,
	PARAMETER_VALUE VARCHAR(2500),
	IDENTIFYING CHAR(1) NOT NULL,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	COMMIT_COUNT BIGINT,
	READ_COUNT BIGINT,
	FILTER_COUNT BIGINT,
	WRITE_COUNT BIGINT,
	READ_SKIP_COUNT BIGINT,
	WRITE_SKIP_COUNT BIGINT,
	PROCESS_SKIP_COUNT BIGINT,
	ROLLBACK_COUNT BIGINT,
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_INSTANCE_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

-- ------------------------------------------------------------------------------------------
-- 4. Text indexes, rebuilt for the new image's collation
-- ------------------------------------------------------------------------------------------
-- postgres:18-alpine sorts text with musl's rules; pgvector/pgvector (Debian) with glibc's. Same
-- locale NAME (en_US.utf8), different ORDER - and a B-tree index is nothing but an order. On a
-- database created by the old image, these two indexes would be silently wrong on the new one: a
-- lookup can walk past a row that is there. PostgreSQL cannot warn, because musl records no
-- collation version to compare. Rebuilding them costs nothing at this size, and on a new database
-- it is a no-op in effect.
REINDEX INDEX idx_product_name;
REINDEX INDEX idx_product_category;
