-- Accounts, and the one that can administer the shop.
--
-- Carried over from the application's V5 verbatim in shape, and read back from the RUNNING database
-- to be sure of it. Starting again at V1 for the reason every extracted service does: a new database
-- has nothing to migrate FROM, so replaying five versions of history would be theatre.
CREATE TABLE users (
    id         BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)                 NOT NULL,

    -- 100 characters because a BCrypt hash is 60 and the column should not need widening the first
    -- time the cost factor or the algorithm changes. The PLAINTEXT is never stored, never logged and
    -- never returned by the API - CustomerResponse has no password field at all.
    password   VARCHAR(100)                NOT NULL,

    full_name  VARCHAR(100)                NOT NULL,
    role       VARCHAR(20)                 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_users_username UNIQUE (username),

    -- The check constraint stays, and it is worth keeping rather than trusting the enum. Hibernate
    -- writes whatever the Java enum says; the database is what stops a bad value arriving by any
    -- other route - a script, a console, a future service - and it is the one guard that survives a
    -- refactor nobody ran the tests for.
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

-- THE SEEDED ADMINISTRATOR, with the same id and the same hash it has always had.
--
-- The id matters now in a way it did not before. `orders.user_id` and `cart.user_id` in
-- order-service's database hold ids issued HERE, and Phase 20d removed the foreign keys that used to
-- tie them together - so the numbers have to line up across two databases with nothing enforcing it.
-- Writing id 1 explicitly makes that a stated fact rather than a consequence of this being the first
-- insert. `SeededAdminMatchesTheOrdersTest` checks it.
--
-- The hash is BCrypt of "admin123", copied over unchanged so that every existing token, script and
-- smoke-test login keeps working. It is a development credential and always has been; it is in Git
-- because it protects nothing.
INSERT INTO users (id, username, password, full_name, role, created_at)
VALUES (
    1,
    'admin',
    '$2a$10$83EZH5ISzQ87x7Llj0PybuyU774SDlI9pFQxlQB2XjwL8j5RZkiQq',
    'Store Administrator',
    'ADMIN',
    CURRENT_TIMESTAMP
);

-- An explicit id does not advance the identity sequence, so the next account registered would be
-- handed id 1 and collide. Same tax as catalog_db's seed, same fix.
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
