-- The catalogue, and this service's schema in its entirety.
--
-- In the monolith's timeline this table was built by V1 and then altered twice: V3 added `category`,
-- V4 added `version`. Here it is created in its final shape as a single V1, because catalog-service's
-- database is new and empty and has no history to preserve. Collapsing migrations is normally
-- forbidden - a checksum mismatch stops the application - and is legitimate exactly once: when the
-- database has never run the originals.
--
-- The lesson V3 taught is still worth keeping even though the file has gone: `category` is nullable
-- with no default, which is the "expand" half of expand/contract. It shipped before the code that
-- filled it, and code that had never heard of the column kept working during the rolling deploy.
--
-- WHAT IS NOT HERE is the point of this phase: there is no stock_quantity column. Stock lives in
-- inventory-service's database, on a different server as far as this service is concerned. No query
-- written here can join to it, which is what makes "services do not read each other's data" a fact
-- about PostgreSQL rather than a rule somebody has to remember in code review.

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12, 2) NOT NULL,
    category    VARCHAR(100),
    -- The optimistic lock. Hibernate increments it on every update and writes
    --     UPDATE products SET ..., version = 4 WHERE id = ? AND version = 3
    -- so an update built on a stale read matches zero rows and fails loudly instead of silently
    -- overwriting whoever got there first.
    --
    -- In Phase 6 this guarded stock, where two concurrent orders for the last unit would both read
    -- 1 and both write 0. That contention moved to inventory-service, which has its own version
    -- column for exactly that reason. What is left here is the rarer case it still covers: two
    -- administrators repricing the same product from the same stale read.
    version     BIGINT         NOT NULL DEFAULT 0
);

-- Supports the "show me everything in this category" queries a catalogue inevitably grows.
CREATE INDEX idx_products_category ON products (category);
