-- Phase 24: inventory-service joins the saga.
--
-- Three tables, one per part of every saga step (see InventorySagaHandler): what this service
-- has already handled, what it holds, and what it has yet to announce.

-- ------------------------------------------------------------------------------------------
-- The OUTBOX, the same table as ecomdemo-app's V10 + V17 (the library that reads it is shared).
-- ------------------------------------------------------------------------------------------
-- Until now inventory sent its only event, `inventory.stock-changed`, straight to Kafka after
-- commit, and said why no outbox: losing one costs a cache entry one TTL of staleness. A saga
-- event is different. A lost `StockReserved` leaves stock held for an order that nobody will ever
-- charge for or confirm - so the durability machinery goes where the loss is now expensive.
-- (`stock-changed` stays as it was; its trade-off has not changed.)
CREATE TABLE outbox_event (
    id              BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID                        NOT NULL UNIQUE,
    aggregate_type  VARCHAR(100)                NOT NULL,
    aggregate_id    VARCHAR(100)                NOT NULL,
    event_type      VARCHAR(100)                NOT NULL,
    payload         TEXT                        NOT NULL,
    trace_parent    VARCHAR(55),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP(6) WITH TIME ZONE,
    attempts        INTEGER                     NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000)
);

CREATE INDEX idx_outbox_event_pending ON outbox_event (published_at, id);
CREATE INDEX idx_outbox_event_published_at ON outbox_event (published_at);

-- ------------------------------------------------------------------------------------------
-- The IDEMPOTENT CONSUMER's ledger: the producer's event id is the primary key, so a redelivered
-- OrderCreated cannot reserve the same order's stock twice.
-- ------------------------------------------------------------------------------------------
CREATE TABLE processed_event (
    event_id     UUID                        PRIMARY KEY,
    event_type   VARCHAR(100)                NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_processed_event_processed_at ON processed_event (processed_at);

-- ------------------------------------------------------------------------------------------
-- What each order holds, so the compensation knows what to give back.
-- ------------------------------------------------------------------------------------------
-- `PaymentFailed` names only an order. Without this table the service receiving it would know
-- that stock must go back and not how much of what. It is also the saga's SEMANTIC LOCK on
-- stock: RESERVED units belong to an order whose outcome is not yet known.
--
-- No foreign key to product_stock, for V1's reason (a product row may be swept), and none to an
-- order: orders live in another service's database.
CREATE TABLE stock_reservation (
    id          BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT                      NOT NULL,
    product_id  BIGINT                      NOT NULL,
    quantity    INTEGER                     NOT NULL,
    status      VARCHAR(20)                 NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT ck_stock_reservation_quantity CHECK (quantity > 0),
    CONSTRAINT ck_stock_reservation_status CHECK (status IN ('RESERVED', 'RELEASED')),

    -- One row per product per order: reserveForOrder adds duplicate lines together first, and
    -- this makes a second reservation of the same order impossible even if processed_event were
    -- somehow bypassed.
    CONSTRAINT uq_stock_reservation_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX idx_stock_reservation_order ON stock_reservation (order_id);
