-- What was sent, and what has already been handled.
--
-- Both tables carried over from the application's V9 verbatim in shape. Starting again at V1, as
-- every extracted service does.
CREATE TABLE notification (
    id         BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- An order id issued by ORDER-SERVICE, believed and not checked. There was never a foreign key
    -- here even when both tables shared a database - Phase 17 decided that deliberately, because a
    -- notification is a record of something that happened and should survive the order being purged.
    -- Now it could not have one anyway.
    order_id   BIGINT                      NOT NULL,

    recipient  VARCHAR(100)                NOT NULL,
    message    VARCHAR(500)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- THE UNIQUE CONSTRAINT IS THE SECOND LINE OF DEFENCE, and it is the one that cannot be raced.
    -- `processed_event` stops a duplicate event being handled twice; this stops two notifications for
    -- one order existing even if that check somehow lost a race. A database constraint is the only
    -- guard that holds when two consumers run at once, which is exactly what scaling this service
    -- out would do.
    CONSTRAINT uq_notification_order UNIQUE (order_id)
);

CREATE INDEX idx_notification_order_id ON notification (order_id);

-- The idempotency ledger, which moved here WITH the consumer it protects.
--
-- It stayed in `messaging` alongside the outbox while both were in one application, and that grouping
-- was always a little wrong: the outbox is about PUBLISHING durably and this is about CONSUMING
-- exactly once. The split forced the question and gave the obvious answer - the table belongs to
-- whoever reads it, and only this service does. `messaging` keeps the outbox and stays in
-- order-service.
CREATE TABLE processed_event (
    -- The event's own id, not a surrogate. It comes from the producer, which is what makes the
    -- primary key do the deduplicating: a second delivery of the same event cannot be inserted.
    event_id     UUID                        PRIMARY KEY,
    event_type   VARCHAR(100)                NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- For the sweep that eventually prunes old markers. Nothing prunes them yet, which is recorded rather
-- than hidden: the table grows by one row per order for ever.
CREATE INDEX idx_processed_event_processed_at ON processed_event (processed_at);
