-- KI-010: notification-service adopts the outbox library to share its idempotent consumer
-- (`ProcessedEvents`), and `@EnableOutbox` brings the relay with it. This service still publishes
-- nothing, so the table stays EMPTY: the relay polls it, finds no rows, and does nothing. It exists
-- because the library's entity maps it and Hibernate validates the schema at startup.
--
-- The same table as ecomdemo-app's V10 + V17 and inventory-service's V3.
CREATE TABLE outbox_event (
    id              BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID                        NOT NULL UNIQUE,
    aggregate_type  VARCHAR(100)                NOT NULL,
    aggregate_id    VARCHAR(100)                NOT NULL,
    event_type      VARCHAR(100)                NOT NULL,
    payload         TEXT                        NOT NULL,
    trace_parent    VARCHAR(55),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP(6) WITH TIME ZONE,
    attempts        INTEGER                     NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000)
);

CREATE INDEX idx_outbox_event_pending ON outbox_event (published_at, id);
CREATE INDEX idx_outbox_event_published_at ON outbox_event (published_at);
