package com.ecomdemo.product;

import com.ecomdemo.common.ApiError;
import com.ecomdemo.product.dto.ProductRequest;
import com.ecomdemo.product.dto.ProductResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/** HTTP entry point for the catalogue. No business logic, no persistence. */
@RestController
@RequestMapping("/api/products")
@Tag(name = "Products", description = "The catalogue: browse, create, update and delete products.")
public class ProductController {

    private final ProductService productService;

    public ProductController(ProductService productService) {
        this.productService = productService;
    }

    @GetMapping
    @Operation(
            summary = "List every product",
            description = "Returns the whole catalogue, unpaged and unsorted. Paging arrives when the catalogue is big enough to need it.")
    @ApiResponse(responseCode = "200", description = "The catalogue, possibly empty")
    public List<ProductResponse> list() {
        return productService.findAll();
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get one product by id")
    @ApiResponse(responseCode = "200", description = "The product")
    @ApiResponse(
            responseCode = "404",
            description = "No product with that id",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ProductResponse get(
            @Parameter(description = "Id of the product", example = "1") @PathVariable Long id) {
        return productService.findById(id);
    }

    /** 201 with a Location header, as a resource-creating POST should. */
    @PostMapping
    @Operation(
            summary = "Create a product",
            description = "The id is generated by the server; anything sent for it is ignored.")
    @ApiResponse(
            responseCode = "201",
            description = "Created. The Location header points at the new product.")
    @ApiResponse(
            responseCode = "400",
            description = "A field failed validation, or the body was not readable JSON",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<ProductResponse> create(@Valid @RequestBody ProductRequest request) {
        ProductResponse created = productService.create(request);
        return ResponseEntity.created(URI.create("/api/products/" + created.id())).body(created);
    }

    @PutMapping("/{id}")
    @Operation(
            summary = "Replace a product",
            description = "A full replacement: every field in the body is written, so omitting one clears it.")
    @ApiResponse(responseCode = "200", description = "The updated product")
    @ApiResponse(
            responseCode = "400",
            description = "A field failed validation, or the body was not readable JSON",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    @ApiResponse(
            responseCode = "404",
            description = "No product with that id",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ProductResponse update(
            @Parameter(description = "Id of the product to replace", example = "1") @PathVariable Long id,
            @Valid @RequestBody ProductRequest request) {
        return productService.update(id, request);
    }

    @DeleteMapping("/{id}")
    @Operation(
            summary = "Delete a product",
            description = "Removing a product that is still in the cart is not prevented yet.")
    @ApiResponse(responseCode = "204", description = "Deleted; no body")
    @ApiResponse(
            responseCode = "404",
            description = "No product with that id",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class)))
    public ResponseEntity<Void> delete(
            @Parameter(description = "Id of the product to delete", example = "1") @PathVariable Long id) {
        productService.delete(id);
        return ResponseEntity.noContent().build();
    }
}
