-- Phase 32: the audit trail of dead-letter replays.
--
-- A dead-lettered saga event is a message nobody could process. Sending it back to its topic is an
-- operator's decision with consequences - it can confirm an order, or charge nothing because the
-- order was already voided - so every replay is recorded: which record, where it went, who sent it,
-- when. The unique key is the record's position in its dead-letter topic, which makes "replay this
-- record" something that can be done once. A replay that fails again lands in the DLT at a NEW
-- offset, and that new record can be replayed in its turn.
CREATE TABLE dead_letter_replay (
    id             BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dlt_topic      VARCHAR(200)                NOT NULL,
    dlt_partition  INTEGER                     NOT NULL,
    dlt_offset     BIGINT                      NOT NULL,
    original_topic VARCHAR(200)                NOT NULL,
    record_key     VARCHAR(200),
    replayed_by    VARCHAR(100)                NOT NULL,
    replayed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_dead_letter_replay_record UNIQUE (dlt_topic, dlt_partition, dlt_offset)
);

CREATE INDEX idx_dead_letter_replay_replayed_at ON dead_letter_replay (replayed_at);
