-- V5: the users table, and the one account that has to exist before anybody can create another.
--
-- Until now the application had no idea who was calling. Every request was anonymous, the cart
-- was shared by the whole world, and any client could create a product. This migration adds the
-- table those distinctions are made from; V6 attaches the cart and the orders to it.

-- --------------------------------------------------------------------------------------------
-- users: who may call the API, and as what
-- --------------------------------------------------------------------------------------------
-- The table is `users`, not `user`: USER is a reserved word in SQL (in PostgreSQL it is the
-- function that returns the current database user), so `select * from user` does not mean what
-- it looks like. Same reasoning as `orders` in V1.
--
-- WHAT IS STORED IN `password`
-- A BCrypt HASH, never the password. The difference is not a detail, it is the whole point:
--   * Encryption is two-way. Something, somewhere, holds a key that turns the ciphertext back
--     into the password — so a leak of the database plus that key is a leak of every password,
--     and users reuse passwords across sites.
--   * Hashing is one-way. There is no key and no inverse. Logging in re-hashes what the client
--     sent and compares the two hashes; nothing in this system can ever produce the original.
-- BCrypt on top of that is *deliberately slow* and *salted*. The salt (random, different per row
-- and stored inside the hash string) means two users with the same password get different hashes,
-- so a stolen table cannot be attacked with one precomputed rainbow table. The cost factor — the
-- `10` in the `$2a$10$` prefix — makes each guess cost real CPU time, which is what keeps a
-- stolen table expensive to brute-force. A general-purpose hash like SHA-256 is the wrong tool
-- here precisely because it is fast.
--
-- The format is `$2a$<cost>$<22-char salt><31-char hash>` and is always exactly 60 characters.
-- The column is VARCHAR(100) rather than CHAR(60) so that raising the cost factor, or moving to
-- a longer format such as Argon2, needs no migration.
CREATE TABLE users (
    id         BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)                 NOT NULL,
    password   VARCHAR(100)                NOT NULL,
    full_name  VARCHAR(100)                NOT NULL,
    role       VARCHAR(20)                 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- The database enforces uniqueness, not the service. A "is this username taken?" check in
    -- Java is a read followed by a write, and two registrations racing between the two both see
    -- "free" and both insert. The unique index is the only check that cannot be raced.
    CONSTRAINT uq_users_username UNIQUE (username),
    -- @Enumerated(STRING) writes the constant's name, so the database can check it.
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

-- --------------------------------------------------------------------------------------------
-- The seeded administrator
-- --------------------------------------------------------------------------------------------
-- Registration through the API only ever creates CUSTOMERs — an endpoint that let the caller
-- choose its own role would be a privilege-escalation hole, not a feature. So the first ADMIN
-- cannot come from the API; it has to be put there by something that already has access to the
-- database, which is this migration.
--
-- The hash below is BCrypt("admin123"), generated once with BCryptPasswordEncoder. It is a
-- THROWAWAY LOCAL DEVELOPMENT CREDENTIAL, in the same spirit as the `ecomdemo/ecomdemo` database
-- password this repository already defaults to, and it is safe in Git only because this
-- application is never exposed. A real deployment changes it immediately — the README says how —
-- because a published default admin password is the same thing as no password at all.
--
-- Note that the hash is written literally rather than computed here: PostgreSQL can hash with
-- pgcrypto and H2 cannot, and a migration that only runs on one engine is a migration that the
-- fast test suite cannot check.
INSERT INTO users (username, password, full_name, role, created_at)
VALUES (
    'admin',
    '$2a$10$83EZH5ISzQ87x7Llj0PybuyU774SDlI9pFQxlQB2XjwL8j5RZkiQq',
    'Store Administrator',
    'ADMIN',
    CURRENT_TIMESTAMP
);
