-- Two tables for Phase 17: what the consumer produced, and what it has already seen.
--
-- ------------------------------------------------------------------------------------------
-- notification: the work the consumer does
-- ------------------------------------------------------------------------------------------
-- A row per notification that would have been sent. Nothing here actually emails anybody - the
-- point of the phase is the messaging, not the mail - so the row IS the side effect, which has
-- the useful property of being something a test and the smoke script can count.
-- NOTE THE DIALECT. `BIGINT GENERATED BY DEFAULT AS IDENTITY` rather than PostgreSQL's
-- `BIGSERIAL`, `TIMESTAMP(6) WITH TIME ZONE` rather than `TIMESTAMPTZ`, and `CURRENT_TIMESTAMP`
-- rather than `now()` - the same portable spelling every migration since V1 uses. It matters
-- because these files run on H2 in the fast Surefire suite as well as on PostgreSQL everywhere
-- else: the first draft of this migration used the PostgreSQL spellings and failed the whole
-- unit suite with `Unknown data type: "TIMESTAMPTZ"`. Flyway does not translate dialects, and a
-- migration is the one kind of code that must run identically on both.
CREATE TABLE notification (
    id              BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT                      NOT NULL,
    recipient       VARCHAR(100)                NOT NULL,
    message         VARCHAR(500)                NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- The phase's "Done when" is "each order produces EXACTLY ONE notification", and this is
    -- what makes that true rather than merely likely. Idempotency is enforced in the consumer by
    -- the processed_event table below; this constraint is the database saying the same thing
    -- independently, so a bug in that logic surfaces as a violation here instead of as a second
    -- notification nobody notices.
    CONSTRAINT uq_notification_order UNIQUE (order_id)
);

-- Every query this table serves is "the notifications for this order".
CREATE INDEX idx_notification_order_id ON notification (order_id);

-- ------------------------------------------------------------------------------------------
-- processed_event: the consumer's memory
-- ------------------------------------------------------------------------------------------
-- Kafka delivers AT LEAST ONCE. That is not a defect to be configured away: a consumer that has
-- done its work and dies before committing its offset will be given the same record again, and
-- so will every consumer in a group after a rebalance. The broker cannot know whether the work
-- happened, because the work happened somewhere else.
--
-- So the consumer has to recognise a record it has already handled, and this table is that
-- memory. The event id is generated by the PRODUCER, travels with the message, and is the same
-- on every redelivery - which is the property the whole scheme rests on. A key generated by the
-- consumer, or a database sequence, would be different each time and would recognise nothing.
CREATE TABLE processed_event (
    -- The event id from the message, not a surrogate key: the primary key IS the identity being
    -- checked, so a duplicate insert is refused by the database rather than by a SELECT that
    -- another thread could race.
    event_id        UUID                        PRIMARY KEY,
    event_type      VARCHAR(100)                NOT NULL,
    processed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Rows here are only ever read by primary key, but they are swept by age: an idempotency table
-- that grows for ever eventually costs more than the duplicates it prevents. Nothing sweeps it
-- yet - a retention job is out of this phase's scope and is recorded as a follow-up - and this
-- index is what that job will use when it arrives.
CREATE INDEX idx_processed_event_processed_at ON processed_event (processed_at);
