-- payment_db, from nothing (Phase 24).
--
-- Three tables, the three parts of this service's one saga step: what it has handled
-- (processed_event), what it decided (payment), and what it has yet to announce (outbox_event).

-- ------------------------------------------------------------------------------------------
-- One row per order, success or decline.
-- ------------------------------------------------------------------------------------------
-- order_id is UNIQUE: charging one order twice is the mistake a payment step must never make,
-- and the database is the one guard that holds even if two copies of an event race.
-- No foreign key: the order lives in another service's database.
CREATE TABLE payment (
    id          BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT                      NOT NULL,
    -- NUMERIC(12,2), the same money type the order service uses for totals (BigDecimal in Java).
    amount      NUMERIC(12, 2)              NOT NULL,
    status      VARCHAR(20)                 NOT NULL,
    reason      VARCHAR(500),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_payment_order UNIQUE (order_id),
    CONSTRAINT ck_payment_status CHECK (status IN ('COMPLETED', 'FAILED')),
    -- A decline must say why; a success has nothing to explain.
    CONSTRAINT ck_payment_reason CHECK ((status = 'FAILED') = (reason IS NOT NULL))
);

-- ------------------------------------------------------------------------------------------
-- The outbox and the idempotent consumer's ledger: the shared library's tables, as in
-- ecomdemo-app (V10, V17, V18) and inventory-service (V3).
-- ------------------------------------------------------------------------------------------
CREATE TABLE outbox_event (
    id              BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID                        NOT NULL UNIQUE,
    aggregate_type  VARCHAR(100)                NOT NULL,
    aggregate_id    VARCHAR(100)                NOT NULL,
    event_type      VARCHAR(100)                NOT NULL,
    payload         TEXT                        NOT NULL,
    trace_parent    VARCHAR(55),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP(6) WITH TIME ZONE,
    attempts        INTEGER                     NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000)
);

CREATE INDEX idx_outbox_event_pending ON outbox_event (published_at, id);
CREATE INDEX idx_outbox_event_published_at ON outbox_event (published_at);

CREATE TABLE processed_event (
    event_id     UUID                        PRIMARY KEY,
    event_type   VARCHAR(100)                NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_processed_event_processed_at ON processed_event (processed_at);
