-- Carts, orders and the audit trail: this service's schema in its entirety.
--
-- Collapsed from the monolith's V1, V5 and V7 into a single V1, for the reason given in every
-- service's first migration: this database is new and empty, so there is no history to preserve and
-- no checksum to break. What that collapse hides is worth stating once - the three-migration sequence
-- recorded how the cart went from a single shared row to one per customer, and that story now lives
-- only in git.
--
-- THE FOREIGN KEYS THAT ARE MISSING ARE THE POINT OF THIS PHASE.
--
-- In the monolith this schema had four cross-feature foreign keys:
--     cart_items.product_id  -> products(id)
--     order_items.product_id -> products(id)
--     carts.customer_id      -> users(id)
--     orders.customer_id     -> users(id)
--
-- All four are gone, because products live in catalog-service's database and users in
-- customer-service's, and PostgreSQL cannot reference a table in another database. The columns
-- remain; only the guarantee has gone. Concretely, this schema can now hold:
--
--   * a cart line for a product that has been deleted from the catalogue (CartService renders it as
--     unavailable; checkout refuses it);
--   * an order belonging to a customer id that no longer exists (nothing notices, and nothing
--     should - an order is a historical record and must outlive the account);
--   * a product_id that never existed at all, if something wrote one.
--
-- The compensating design is that order_items snapshots product_name and unit_price at purchase
-- time, so an order can be rendered completely without ever resolving product_id. The column is
-- there to answer "which product was this?", not to render the line - which was already true in
-- Phase 0, and is now the only thing that makes these rows readable at all.

CREATE TABLE carts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The `sub` claim of a verified token. No foreign key, and none possible.
    customer_id BIGINT NOT NULL,
    -- One cart each. This is what makes "the current user's cart" a well-defined phrase, and it is
    -- enforced here rather than trusted to the service that creates carts.
    CONSTRAINT uq_carts_customer UNIQUE (customer_id)
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    -- This foreign key survives: both ends are in this database. Database-per-service forbids joins
    -- across services, not within one, and order-service's own schema is as relational as it ever
    -- was.
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id)
);

-- placed_at is TIMESTAMP WITH TIME ZONE because Order.placedAt is an Instant - a point in time, not
-- a wall clock reading. total_amount is stored rather than derived: an order is a historical record
-- of what was actually paid.
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT                      NOT NULL,
    placed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    total_amount NUMERIC(12, 2)              NOT NULL
);

-- product_name and unit_price are copied from the catalogue at checkout, not read through
-- product_id - and after Phase 20 they could not be read through it even if somebody wanted to.
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(255)   NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

-- An audit trail for every attempt to place an order, successful or not.
--
-- Written with Propagation.REQUIRES_NEW, which suspends the caller's transaction and commits this
-- row in one of its own. That is the point: when the main transaction rolls back - out of stock, an
-- empty cart, a version conflict - the order vanishes and this row remains.
--
-- It matters more after Phase 20 than before. A checkout now reserves stock in another service
-- before writing anything here, so when it fails these rows are the only local evidence that the
-- attempt happened at all - and the only place to look when stock is missing and no order explains
-- it.
--
-- It deliberately has no foreign key to orders. A failed attempt has no order to point at, and an
-- audit row must never be deletable as a side effect of deleting what it describes.
CREATE TABLE order_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    outcome     VARCHAR(40)                 NOT NULL,
    detail      VARCHAR(500)                NOT NULL,
    order_id    BIGINT
);

-- PostgreSQL never indexes the referencing side of a foreign key on its own, and every join fetch in
-- CartRepository and OrderRepository depends on these.
CREATE INDEX idx_cart_items_cart   ON cart_items (cart_id);
CREATE INDEX idx_order_items_order ON order_items (order_id);

-- Every order listing is "this customer's orders, newest first".
CREATE INDEX idx_orders_customer ON orders (customer_id, placed_at DESC, id DESC);

-- Audit tables are read newest-first, and by outcome when something has gone wrong.
CREATE INDEX idx_order_audit_occurred_at ON order_audit (occurred_at DESC, id DESC);
CREATE INDEX idx_order_audit_outcome     ON order_audit (outcome);
