-- The transactional outbox: the event, written to the same database as the order, in the same
-- transaction as the order.
--
-- ------------------------------------------------------------------------------------------
-- WHAT THIS FIXES, precisely
-- ------------------------------------------------------------------------------------------
-- Phase 17 published AFTER_COMMIT: the order committed, and then, on another thread, the event
-- was sent to Kafka. Two systems, two writes, no shared transaction - the DUAL-WRITE problem.
-- Between those two writes sits a window in which the process can die or the broker can be
-- unreachable, and the result is an order that exists with nothing published for it and nothing
-- anywhere that knows the event is missing.
--
-- That window was not theorised, it was MEASURED. Phase 17's failure test stopped the broker and
-- placed orders: four orders were committed, four notifications were never written, and the loss
-- was permanent. `docs/test-reports/phase-17.md` section 5 has the numbers.
--
-- Retries do not fix it, and this is the part worth sitting with. A retry needs something to
-- retry FROM, and if the only copy of the event was in the memory of a process that has now
-- exited, there is nothing to retry from. The fix cannot be better error handling around the
-- send; it has to be that the event is DURABLE before the send is ever attempted. The only
-- storage that can be made durable atomically with the order is the database the order is
-- already being written to - so the event goes in a table, in the order's own transaction, and a
-- separate relay reads that table and does the sending.
--
-- The guarantee changes from "the event is published unless something goes wrong" to "the event
-- is published AT LEAST ONCE, eventually". At-least-once, not exactly-once: the relay can publish
-- a row and die before marking it sent, and will then publish it again. That is deliberate and it
-- is the whole reason Phase 17 built `processed_event` first - the consumer already recognises a
-- duplicate by event id, so the duplicate the outbox can create is one the consumer was already
-- built to absorb. A design where the producer promised exactly-once would be a design that
-- lies.
--
-- ------------------------------------------------------------------------------------------
-- outbox_event
-- ------------------------------------------------------------------------------------------
-- The same portable dialect every migration since V1 uses: `BIGINT GENERATED BY DEFAULT AS
-- IDENTITY` rather than PostgreSQL's `BIGSERIAL`, `TIMESTAMP(6) WITH TIME ZONE` rather than
-- `TIMESTAMPTZ`, `CURRENT_TIMESTAMP` rather than `now()`. These files run on H2 in the fast
-- Surefire suite and on PostgreSQL everywhere else, Flyway does not translate dialects, and V9's
-- first draft failed the entire unit suite by forgetting exactly this.
CREATE TABLE outbox_event (
    -- A SEQUENCE, and it is doing real work: it is the publication ORDER. The relay reads
    -- pending rows by ascending id, so events leave the outbox in the order they were committed.
    -- `created_at` could not do this job - two rows can share a timestamp, and a clock that steps
    -- backwards would reorder history - whereas an identity column is monotonic by construction.
    id              BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The IDEMPOTENCY key, and a different thing from the primary key above, which is why both
    -- columns exist. This is the id that travels inside the message and that `processed_event`
    -- checks on the consumer side. It is generated once, when the row is written, so every
    -- republication of this row carries the SAME id and is recognised as the duplicate it is.
    -- UNIQUE because a second row claiming the same event id would defeat that recognition.
    event_id        UUID                        NOT NULL UNIQUE,

    -- What the event is about. Not used for routing today - the relay maps event_type to a topic
    -- - but this is the pair that makes an outbox table reusable by the next aggregate that needs
    -- one, and it is what a human reads first when asking "what is stuck in here?".
    aggregate_type  VARCHAR(100)                NOT NULL,
    aggregate_id    VARCHAR(100)                NOT NULL,
    event_type      VARCHAR(100)                NOT NULL,

    -- The message body, serialised at WRITE time, not at publication time.
    --
    -- This is a correctness property rather than an optimisation. The payload is the state of the
    -- order as it was when the order was placed; serialising later, in the relay, would mean
    -- re-reading entities that may have changed since - and publishing "the order as it is now"
    -- under an event that claims to describe what happened then. Freezing the bytes inside the
    -- transaction makes the event a record of a fact rather than a query executed later.
    --
    -- TEXT, which both H2 and PostgreSQL accept (the Spring Batch schema in V7 relies on the same
    -- thing). Not PostgreSQL's `JSONB`: nothing here queries INTO the payload, and JSONB would
    -- not survive the H2 run.
    payload         TEXT                        NOT NULL,

    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- NULL means pending. This single nullable column is the entire state machine, and a
    -- deliberate alternative to a `status VARCHAR` with values like 'PENDING'/'SENT': a status
    -- column can hold 'SENT' with no timestamp, or a typo, and needs a CHECK constraint to stop
    -- it. A nullable timestamp cannot be inconsistent with itself - it either records when the
    -- row was published or it says it has not been.
    published_at    TIMESTAMP(6) WITH TIME ZONE,

    -- Bookkeeping for the row that will not go. `attempts` is what turns "Kafka is down" into
    -- something visible and countable rather than a silent retry loop, and `last_error` is what
    -- stops the investigation being "reproduce it and watch the logs".
    attempts        INTEGER                     NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000)
);

-- The relay's only query is "the oldest pending rows", which is `WHERE published_at IS NULL ORDER
-- BY id`. This index serves exactly that, and the column order is the point: `published_at` first
-- narrows to the pending rows, `id` then supplies them already sorted, so the query needs no sort
-- step at all.
--
-- It is also, happily, the index that gets SMALLER as the system works correctly. The interesting
-- entries are the pending ones, and a healthy outbox has almost none.
CREATE INDEX idx_outbox_event_pending ON outbox_event (published_at, id);

-- The cleanup job's query: published rows older than the retention window. An outbox that is
-- never swept grows by one row per order for ever, and the table whose whole value is being
-- quick to scan for a handful of pending rows becomes the largest table in the database.
CREATE INDEX idx_outbox_event_published_at ON outbox_event (published_at);
