-- V1: the schema as it stood at the end of Phase 4.
--
-- Until now Hibernate built these tables from the entity classes on every start
-- (spring.jpa.hibernate.ddl-auto=update). From this migration on, the database is built by
-- Flyway and Hibernate only checks that what it finds matches the entities (ddl-auto=validate).
--
-- Flyway records this file in its own `flyway_schema_history` table together with a checksum of
-- its contents. That is why an applied migration is NEVER edited: the checksum would no longer
-- match, Flyway would refuse to start, and - worse - databases that had already run the old
-- version would silently disagree with those that ran the new one. A mistake in an applied
-- migration is corrected by a NEW migration (see V3).
--
-- The DDL below is deliberately the same shape Hibernate generated, because ddl-auto=validate
-- compares the two on every start: table and column names, types, lengths, and nullability.
-- Two things are intentionally better than Hibernate's version:
--   * constraints have readable names instead of fk1uobyhgl1wvgt1jpccia8xxs3
--   * the foreign keys spell out what happens to children when a parent goes away
-- Hibernate's validator does not look at constraint names, foreign keys or indexes, so both
-- changes are free.

-- --------------------------------------------------------------------------------------------
-- product: the catalogue
-- --------------------------------------------------------------------------------------------
-- GENERATED BY DEFAULT AS IDENTITY is the SQL-standard form of an auto-incrementing column and
-- is what @GeneratedValue(strategy = IDENTITY) expects on PostgreSQL. "BY DEFAULT" (rather than
-- "ALWAYS") still allows an explicit id to be inserted, which data loads and tests rely on.
CREATE TABLE product (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255)   NOT NULL,
    description    VARCHAR(1000),
    price          NUMERIC(12, 2) NOT NULL,
    stock_quantity INTEGER        NOT NULL
);

-- --------------------------------------------------------------------------------------------
-- cart and cart_item: the single shared cart (one row until Phase 8 introduces users)
-- --------------------------------------------------------------------------------------------
CREATE TABLE cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE cart_item (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    -- The Cart entity owns its items (cascade = ALL, orphanRemoval = true), so the database is
    -- told the same thing: deleting a cart deletes its lines.
    CONSTRAINT fk_cart_item_cart    FOREIGN KEY (cart_id)    REFERENCES cart (id) ON DELETE CASCADE,
    -- A product that is in somebody's cart must not vanish underneath it. RESTRICT makes the
    -- delete fail instead of leaving a dangling row.
    CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT
);

-- Every read of the cart joins through this column, and the foreign key alone does not create an
-- index in PostgreSQL (unlike the primary key, which does).
CREATE INDEX idx_cart_item_cart ON cart_item (cart_id);

-- --------------------------------------------------------------------------------------------
-- orders and order_item: placed orders
-- --------------------------------------------------------------------------------------------
-- The table is `orders`, not `order`: ORDER is a reserved word in SQL.
CREATE TABLE orders (
    id           BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status       VARCHAR(20)              NOT NULL,
    total_amount NUMERIC(12, 2)           NOT NULL,
    -- @Enumerated(STRING) writes the constant's name, so the database can check it. Adding a
    -- status in a later phase means a new migration that drops and recreates this constraint.
    CONSTRAINT ck_orders_status CHECK (status IN ('PLACED'))
);

-- No foreign key to product here on purpose: an order line keeps a COPY of the product's name
-- and price as they were at checkout, so repricing or deleting a product cannot rewrite history.
CREATE TABLE order_item (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(255)   NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_item_order ON order_item (order_id);
