-- The schema as it stood at the end of Phase 4, now written down instead of generated.
--
-- Up to this point Hibernate created these tables from the @Entity classes. From here on Flyway
-- owns them and Hibernate only validates, which is why this file has to reproduce what Hibernate
-- produced closely enough for `ddl-auto: validate` to agree with it.
--
-- Two things are deliberately better than the generated version:
--   * constraints are named. Hibernate called one of these fk1re40cjegsfvw58xrkdp6bac6, which tells
--     you nothing when it is the name in a constraint-violation error at 3am.
--   * foreign key columns are indexed. PostgreSQL indexes the referenced side of a foreign key
--     automatically but never the referencing side, so every join fetch in CartRepository and
--     OrderRepository was scanning the whole table.

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255)   NOT NULL,
    description    VARCHAR(1000),
    price          NUMERIC(12, 2) NOT NULL,
    stock_quantity INTEGER        NOT NULL
);

-- One row, id 1, for as long as there are no users (Phase 8). The id is assigned by the application
-- rather than generated, so this table has no identity column.
CREATE TABLE carts (
    id BIGINT PRIMARY KEY
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_cart    FOREIGN KEY (cart_id)    REFERENCES carts (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- placed_at is TIMESTAMP WITH TIME ZONE because Order.placedAt is an Instant - a point in time, not
-- a wall clock reading. total_amount is stored rather than derived: an order is a historical record
-- of what was actually paid.
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    total_amount NUMERIC(12, 2)              NOT NULL
);

-- product_name and unit_price are copied from the product at checkout, not read through product_id.
-- The foreign key is kept for traceability only; renaming or repricing a product must not rewrite
-- an order that has already been placed.
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(255)   NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_cart_items_cart     ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product  ON cart_items (product_id);
CREATE INDEX idx_order_items_order   ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

-- OrderRepository.findAllWithItems sorts by placed_at desc, id desc on every call to GET /api/orders.
CREATE INDEX idx_orders_placed_at ON orders (placed_at DESC, id DESC);
