-- V4: the two pieces of schema that Phase 6 needs — a version counter for optimistic locking,
-- and an audit table that records every checkout attempt, successful or not.

-- --------------------------------------------------------------------------------------------
-- product.version: the optimistic lock
-- --------------------------------------------------------------------------------------------
-- Two checkouts for the last unit can both read stock_quantity = 1, both decide there is enough,
-- and both write 0. One unit is sold twice. That is the lost-update anomaly, and no isolation
-- level below SERIALIZABLE prevents it, because neither transaction does anything illegal on its
-- own — they simply do not see each other.
--
-- OPTIMISTIC locking closes it without a single lock being taken. Hibernate reads the version
-- along with the row and writes
--     UPDATE product SET stock_quantity = ?, version = version + 1 WHERE id = ? AND version = ?
-- The second writer's WHERE no longer matches (the first writer bumped the version), the UPDATE
-- reports 0 rows changed, and Hibernate raises OptimisticLockException instead of overwriting.
-- Nobody waits on anybody; the loser is told to try again.
--
-- NOT NULL DEFAULT 0 because the table already has rows: without the default, adding a NOT NULL
-- column to a non-empty table fails, and Hibernate would then read a null version and treat every
-- existing product as a brand-new, unsaved entity.
ALTER TABLE product ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- --------------------------------------------------------------------------------------------
-- order_audit: what was attempted, whatever the outcome
-- --------------------------------------------------------------------------------------------
-- The point of this table is the REJECTED rows. A rejected checkout rolls its transaction back,
-- so if the audit were written by that same transaction the evidence would disappear along with
-- the failure — the one case anyone actually wants a record of. The audit is therefore written in
-- its OWN transaction (Propagation.REQUIRES_NEW): it commits while the outer transaction is still
-- open and survives that transaction's rollback.
--
-- WHY THERE IS NO FOREIGN KEY ON order_id
-- That independence cuts both ways. A PLACED row names an order whose INSERT has not committed
-- yet, so a foreign key would be checked against a row the audit transaction cannot see and the
-- audit would fail. REJECTED rows have no order at all and leave the column NULL. An audit table
-- is a log, not a relation: it must be able to outlive, and disagree with, the data it describes.
CREATE TABLE order_audit (
    id          BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT,
    outcome     VARCHAR(20)                 NOT NULL,
    detail      VARCHAR(500)                NOT NULL,
    recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_order_audit_outcome CHECK (outcome IN ('PLACED', 'REJECTED'))
);

-- The audit is read newest-first ("what happened during the incident?"), never by id.
CREATE INDEX idx_order_audit_recorded_at ON order_audit (recorded_at);
