-- An audit trail for every attempt to place an order, successful or not.
--
-- Written with Propagation.REQUIRES_NEW, which suspends the caller's transaction and commits this
-- row in one of its own. That is the point: when the main transaction rolls back - out of stock, an
-- empty cart, a version conflict - the order and the stock changes vanish, and this row remains.
--
-- It deliberately has no foreign key to orders. A failed attempt has no order to point at, and an
-- audit row must never be deletable as a side effect of deleting what it describes.
CREATE TABLE order_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    outcome     VARCHAR(40)                 NOT NULL,
    detail      VARCHAR(500)                NOT NULL,
    order_id    BIGINT
);

-- Audit tables are read newest-first, and by outcome when something has gone wrong.
CREATE INDEX idx_order_audit_occurred_at ON order_audit (occurred_at DESC, id DESC);
CREATE INDEX idx_order_audit_outcome     ON order_audit (outcome);
