-- Real users, at last. Until now the application had exactly one anonymous shopper.
--
-- The table is called `users` rather than `user`: USER is a reserved word in PostgreSQL (it returns
-- the current session user), so `CREATE TABLE user` needs quoting everywhere it is mentioned.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)                NOT NULL,
    -- BCrypt output is always 60 characters. The extra room costs nothing and means a future move to
    -- Argon2 (whose hashes are longer) needs no migration of its own.
    password_hash VARCHAR(100)                NOT NULL,
    display_name  VARCHAR(100),
    -- One role per user, stored as its name rather than its ordinal: reordering the enum must never
    -- silently turn every CUSTOMER into an ADMIN. A user needing two roles would mean a join table.
    role          VARCHAR(20)                 NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- The unique constraint above is what actually prevents duplicate registrations. The service checks
-- first and returns a friendly 409, but two simultaneous registrations would both pass that check -
-- the database is the only thing that can decide the race.
CREATE INDEX idx_users_role ON users (role);

-- The seeded administrator.
--
-- The hash below is BCrypt of the password 'admin123', which the README states openly. Committing it
-- is deliberate and safe for the same reason the local PostgreSQL password in application-dev.yml is:
-- it unlocks a throwaway local database and nothing else. BCrypt is one-way, so the hash itself
-- reveals nothing even if this file is read by someone who does not know the password.
--
-- A real deployment changes it. There is no path from this row to a production credential.
INSERT INTO users (email, password_hash, display_name, role, created_at) VALUES
    ('admin@ecomdemo.local',
     '$2a$10$ScyXrR11DmqB3w0vrOE7yOD1Nbn9JKxldxn.JoPIB3dFGiaqx5i3W',
     'Seeded Administrator',
     'ADMIN',
     CURRENT_TIMESTAMP);
