-- The cart stops being a singleton and becomes one cart per customer.
--
-- carts and cart_items are dropped and recreated rather than altered. The single row they held was
-- an artifact of there being no users - Cart.SHARED_CART_ID, seeded by V2 - not data anyone owns, and
-- recreating gives carts.id a real identity column. Altering a plain BIGINT primary key into an
-- identity column afterwards is possible but spelled differently on PostgreSQL and H2, and the
-- migrations have to run on both.
DROP TABLE cart_items;
DROP TABLE carts;

CREATE TABLE carts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    CONSTRAINT fk_carts_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    -- One cart each. This is what makes "the current user's cart" a well-defined phrase, and it is
    -- enforced here rather than trusted to the service that creates carts.
    CONSTRAINT uq_carts_customer UNIQUE (customer_id)
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_cart    FOREIGN KEY (cart_id)    REFERENCES carts (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_cart_items_cart    ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product ON cart_items (product_id);

-- Orders gain an owner, NULLABLE on purpose.
--
-- Orders placed before this phase have no owner and cannot be given one - there was no such concept
-- when they were placed. Making the column NOT NULL would mean deleting them. Nullable keeps the
-- history intact at the cost of rows that belong to nobody: no customer's query returns them, since
-- every one of those filters on customer_id = ?. This is the expand step from Phase 5 applied to a
-- column that will simply never be tightened.
ALTER TABLE orders ADD COLUMN customer_id BIGINT;
ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id);

-- Every order listing is now "this customer's orders, newest first".
CREATE INDEX idx_orders_customer ON orders (customer_id, placed_at DESC, id DESC);
