-- The consumer side of Phase 17: what a notification is, and what stops one being sent twice.

-- One row per confirmation "sent" for an order. Sending is a log line in this phase; the row is the
-- durable record that it happened, and the thing an integration test can assert on.
--
-- No foreign key to orders, and none to customers.
--
-- That is deliberate and is a property of consuming events rather than reading tables. This consumer
-- acts on what the event told it, not on what it can look up - so it must be able to record a
-- notification for an order that has since been deleted, and it must not fail because a row it never
-- asked about is missing. Today the producer is in the same database and a foreign key would work;
-- the moment the notification service moves out (Phase 19 onwards) it would not, and a schema that
-- has to be unpicked later is worse than one that was honest from the start.
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    UUID                        NOT NULL,
    order_id    BIGINT                      NOT NULL,
    customer_id BIGINT                      NOT NULL,
    message     VARCHAR(500)                NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Read by customer, newest first - the shape GET /api/notifications asks for.
CREATE INDEX idx_notifications_customer ON notifications (customer_id, created_at DESC, id DESC);

-- Lets "was a notification already written for this event?" be answered without a table scan, and
-- makes a duplicate visible in a query rather than only in a count.
CREATE INDEX idx_notifications_event ON notifications (event_id);

-- The idempotency ledger: one row per event this application has finished handling.
--
-- Kafka's delivery guarantee is at-least-once. A consumer that crashes after doing its work but
-- before its offset is committed will be handed the same record again on restart, and a rebalance
-- can do the same to a consumer that did not crash at all. Neither is an error - it is the
-- guarantee working as designed, and the consumer is what has to absorb it.
--
-- event_id is the PRIMARY KEY, and that is the mechanism rather than a nicety. The uniqueness is
-- enforced by the database, inside the same transaction that writes the notification, so two
-- deliveries racing each other cannot both pass a check-then-act: one of them loses on the insert.
-- An `if (!exists) { handle(); }` in Java alone has a window between the check and the write.
CREATE TABLE processed_events (
    event_id     UUID                        PRIMARY KEY,
    event_type   VARCHAR(100)                NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- This table grows forever, one row per event, and nothing here deletes from it. That is a real
-- operational cost and naming it is part of the lesson: the honest fix is to expire rows older than
-- the longest possible re-delivery window, which needs a scheduler this phase does not introduce.
CREATE INDEX idx_processed_events_processed_at ON processed_events (processed_at);
