@startuml
set separator none
title Auth

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("EcomdemoApplication.EcomdemoApplication_boundary", "EcomdemoApplication", $tags="") {
  Component(EcomdemoApplication.EcomdemoApplication.Security, "Security", $techn="Module", $descr="", $tags="", $link="")
  Component(EcomdemoApplication.EcomdemoApplication.Auth, "Auth", $techn="Module", $descr="", $tags="", $link="")
  Component(EcomdemoApplication.EcomdemoApplication.Sharedkernel, "Shared kernel", $techn="Module", $descr="", $tags="", $link="")
}

Rel(EcomdemoApplication.EcomdemoApplication.Auth, EcomdemoApplication.EcomdemoApplication.Sharedkernel, "depends on", $techn="", $tags="", $link="")
Rel(EcomdemoApplication.EcomdemoApplication.Auth, EcomdemoApplication.EcomdemoApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(EcomdemoApplication.EcomdemoApplication.Security, EcomdemoApplication.EcomdemoApplication.Sharedkernel, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml