@startuml
title <size:24>Redis client certificate</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("EcomdemoApplication_boundary", "EcomdemoApplication", $tags="") {
  Container_Boundary("EcomdemoApplication.EcomdemoApplication_boundary", "EcomdemoApplication", $tags="") {
    Component(EcomdemoApplication.EcomdemoApplication.Redisclientcertificate, "Redis client certificate", $techn="Module", $descr="", $tags="", $link="")
  }

}

SHOW_LEGEND(true)
hide stereotypes
@enduml