package com.ecomdemo.catalog;

import com.ecomdemo.clients.catalog.CatalogGateway;
import com.ecomdemo.clients.catalog.ProductSnapshot;
import com.ecomdemo.clients.catalog.ProductWrite;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * The PUBLIC {@code /api/products}, which forwards to catalog-service.
 *
 * <h2>Why a proxy, rather than pointing shoppers at catalog-service</h2>
 *
 * <p>Because the split is not supposed to be visible from the outside, and because the alternative
 * contradicts the boundary catalog-service was given. Every path on that service requires a service
 * token; publishing it to browsers would mean either making its reads anonymous — "open because of
 * who happens to call it", which is not a boundary — or handing shoppers a credential.
 *
 * <p>So the application stays the public face, exactly as it did for stock in Phase 20b, and the
 * 270 smoke checks keep driving the same URLs. The ADMIN rules on writes are unchanged and still
 * live in this application's {@code SecurityConfig}, which is where the human's token actually is;
 * catalog-service only ever sees {@code ecomdemo-app}.
 *
 * <p><strong>This class is temporary and should not grow.</strong> A per-service proxy hand-written
 * in the application is what an API gateway exists to replace, and Phase 21 is the API gateway. It
 * forwards and does nothing else: no mapping worth the name, no business rule, no caching. The day
 * it acquires one of those is the day it stops being a proxy.
 */
@RestController
@RequestMapping("/api/products")
@Tag(name = "Products", description = "The catalogue. Reads are public; writes require ADMIN.")
class ProductController {

    private final CatalogGateway catalogue;

    ProductController(CatalogGateway catalogue) {
        this.catalogue = catalogue;
    }

    @GetMapping
    @Operation(
            summary = "List every product",
            description = "The whole catalogue, unpaged. Public: no account needed to look in the window.")
    List<ProductSnapshot> list() {
        return catalogue.findAll();
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get one product by id")
    ProductSnapshot get(
            @Parameter(description = "Id of the product", example = "1") @PathVariable Long id) {
        return catalogue.requireProduct(id);
    }

    @PostMapping
    @SecurityRequirement(name = "bearerAuth")
    @Operation(
            summary = "Create a product (ADMIN)",
            description = "The id is generated by the catalogue; anything sent for it is ignored.")
    ResponseEntity<ProductSnapshot> create(@Valid @RequestBody ProductWrite request) {
        ProductSnapshot created = catalogue.create(request);
        return ResponseEntity.created(URI.create("/api/products/" + created.id())).body(created);
    }

    @PutMapping("/{id}")
    @SecurityRequirement(name = "bearerAuth")
    @Operation(summary = "Replace a product (ADMIN)")
    ProductSnapshot update(
            @Parameter(description = "Id of the product", example = "1") @PathVariable Long id,
            @Valid @RequestBody ProductWrite request) {
        return catalogue.update(id, request);
    }

    @DeleteMapping("/{id}")
    @SecurityRequirement(name = "bearerAuth")
    @Operation(summary = "Delete a product (ADMIN)")
    ResponseEntity<Void> delete(
            @Parameter(description = "Id of the product", example = "1") @PathVariable Long id) {
        catalogue.delete(id);
        return ResponseEntity.noContent().build();
    }
}
